// AUTO-GENERATED by protoc-gen-webviewrpc
using Cysharp.Threading.Tasks;
using Google.Protobuf;
using WebViewRPC;

namespace HelloWorld
{
    public interface IHelloServiceClient
    {
        
        UniTask<HelloResponse> SayHello(HelloRequest request);
        
    }

    public class HelloServiceClient : IHelloServiceClient
    {
        private readonly WebViewRpcClient _rpcClient;

        public HelloServiceClient(WebViewRpcClient rpcClient)
        {
            this._rpcClient = rpcClient;
        }

        
        public async UniTask<HelloResponse> SayHello(HelloRequest request)
        {
            var response = await _rpcClient.CallMethod<HelloResponse>("HelloService.SayHello", request);
            return response;
        }
        
    }
}
