// AUTO-GENERATED by protoc-gen-webviewrpc
using System.Threading.Tasks;
using Google.Protobuf;
using WebViewRPC;

namespace HelloWorld
{
    public class HelloServiceClient
    {
        private readonly WebViewRpcClient _rpcClient;

        public HelloServiceClient(WebViewRpcClient rpcClient)
        {
            _rpcClient = rpcClient;
        }

        
        public async Task<HelloResponse> SayHello(HelloRequest request)
        {
            return await _rpcClient.CallMethod<HelloResponse>("HelloService.SayHello", request);
        }
        
    }
}
