// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: RpcEnvelope.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WebViewRPC {

  /// <summary>Holder for reflection information generated from RpcEnvelope.proto</summary>
  public static partial class RpcEnvelopeReflection {

    #region Descriptor
    /// <summary>File descriptor for RpcEnvelope.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RpcEnvelopeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFScGNFbnZlbG9wZS5wcm90bxIKV2ViVmlld1JQQyKNAQoLUnBjRW52ZWxv",
            "cGUSEQoJcmVxdWVzdElkGAEgASgJEhEKCWlzUmVxdWVzdBgCIAEoCBIOCgZt",
            "ZXRob2QYAyABKAkSDwoHcGF5bG9hZBgEIAEoDBINCgVlcnJvchgFIAEoCRIo",
            "CgljaHVua0luZm8YBiABKAsyFS5XZWJWaWV3UlBDLkNodW5rSW5mbyJeCglD",
            "aHVua0luZm8SEgoKY2h1bmtTZXRJZBgBIAEoCRISCgpjaHVua0luZGV4GAIg",
            "ASgFEhMKC3RvdGFsQ2h1bmtzGAMgASgFEhQKDG9yaWdpbmFsU2l6ZRgEIAEo",
            "BUINqgIKV2ViVmlld1JQQ2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::WebViewRPC.RpcEnvelope), global::WebViewRPC.RpcEnvelope.Parser, new[]{ "RequestId", "IsRequest", "Method", "Payload", "Error", "ChunkInfo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::WebViewRPC.ChunkInfo), global::WebViewRPC.ChunkInfo.Parser, new[]{ "ChunkSetId", "ChunkIndex", "TotalChunks", "OriginalSize" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RpcEnvelope : pb::IMessage<RpcEnvelope>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RpcEnvelope> _parser = new pb::MessageParser<RpcEnvelope>(() => new RpcEnvelope());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RpcEnvelope> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WebViewRPC.RpcEnvelopeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RpcEnvelope() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RpcEnvelope(RpcEnvelope other) : this() {
      requestId_ = other.requestId_;
      isRequest_ = other.isRequest_;
      method_ = other.method_;
      payload_ = other.payload_;
      error_ = other.error_;
      chunkInfo_ = other.chunkInfo_ != null ? other.chunkInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RpcEnvelope Clone() {
      return new RpcEnvelope(this);
    }

    /// <summary>Field number for the "requestId" field.</summary>
    public const int RequestIdFieldNumber = 1;
    private string requestId_ = "";
    /// <summary>
    /// 각 RPC 호출마다 구분하기 위한 고유 ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RequestId {
      get { return requestId_; }
      set {
        requestId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "isRequest" field.</summary>
    public const int IsRequestFieldNumber = 2;
    private bool isRequest_;
    /// <summary>
    /// true이면 "요청(request)", false이면 "응답(response)"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsRequest {
      get { return isRequest_; }
      set {
        isRequest_ = value;
      }
    }

    /// <summary>Field number for the "method" field.</summary>
    public const int MethodFieldNumber = 3;
    private string method_ = "";
    /// <summary>
    /// 호출할 메서드 이름, 예: "HelloService.SayHello"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Method {
      get { return method_; }
      set {
        method_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 4;
    private pb::ByteString payload_ = pb::ByteString.Empty;
    /// <summary>
    /// 실제 요청/응답 메시지의 Protobuf 직렬화 바이트
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Payload {
      get { return payload_; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 5;
    private string error_ = "";
    /// <summary>
    /// 예외나 오류 메시지 (에러 발생 시 사용)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chunkInfo" field.</summary>
    public const int ChunkInfoFieldNumber = 6;
    private global::WebViewRPC.ChunkInfo chunkInfo_;
    /// <summary>
    /// 청킹 정보 (optional - 청킹이 필요한 경우에만 설정)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::WebViewRPC.ChunkInfo ChunkInfo {
      get { return chunkInfo_; }
      set {
        chunkInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RpcEnvelope);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RpcEnvelope other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RequestId != other.RequestId) return false;
      if (IsRequest != other.IsRequest) return false;
      if (Method != other.Method) return false;
      if (Payload != other.Payload) return false;
      if (Error != other.Error) return false;
      if (!object.Equals(ChunkInfo, other.ChunkInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RequestId.Length != 0) hash ^= RequestId.GetHashCode();
      if (IsRequest != false) hash ^= IsRequest.GetHashCode();
      if (Method.Length != 0) hash ^= Method.GetHashCode();
      if (Payload.Length != 0) hash ^= Payload.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (chunkInfo_ != null) hash ^= ChunkInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RequestId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RequestId);
      }
      if (IsRequest != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsRequest);
      }
      if (Method.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Method);
      }
      if (Payload.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Payload);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Error);
      }
      if (chunkInfo_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(ChunkInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RequestId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RequestId);
      }
      if (IsRequest != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsRequest);
      }
      if (Method.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Method);
      }
      if (Payload.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Payload);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Error);
      }
      if (chunkInfo_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(ChunkInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RequestId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RequestId);
      }
      if (IsRequest != false) {
        size += 1 + 1;
      }
      if (Method.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Method);
      }
      if (Payload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (chunkInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ChunkInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RpcEnvelope other) {
      if (other == null) {
        return;
      }
      if (other.RequestId.Length != 0) {
        RequestId = other.RequestId;
      }
      if (other.IsRequest != false) {
        IsRequest = other.IsRequest;
      }
      if (other.Method.Length != 0) {
        Method = other.Method;
      }
      if (other.Payload.Length != 0) {
        Payload = other.Payload;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.chunkInfo_ != null) {
        if (chunkInfo_ == null) {
          ChunkInfo = new global::WebViewRPC.ChunkInfo();
        }
        ChunkInfo.MergeFrom(other.ChunkInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RequestId = input.ReadString();
            break;
          }
          case 16: {
            IsRequest = input.ReadBool();
            break;
          }
          case 26: {
            Method = input.ReadString();
            break;
          }
          case 34: {
            Payload = input.ReadBytes();
            break;
          }
          case 42: {
            Error = input.ReadString();
            break;
          }
          case 50: {
            if (chunkInfo_ == null) {
              ChunkInfo = new global::WebViewRPC.ChunkInfo();
            }
            input.ReadMessage(ChunkInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RequestId = input.ReadString();
            break;
          }
          case 16: {
            IsRequest = input.ReadBool();
            break;
          }
          case 26: {
            Method = input.ReadString();
            break;
          }
          case 34: {
            Payload = input.ReadBytes();
            break;
          }
          case 42: {
            Error = input.ReadString();
            break;
          }
          case 50: {
            if (chunkInfo_ == null) {
              ChunkInfo = new global::WebViewRPC.ChunkInfo();
            }
            input.ReadMessage(ChunkInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 청크 정보
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ChunkInfo : pb::IMessage<ChunkInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ChunkInfo> _parser = new pb::MessageParser<ChunkInfo>(() => new ChunkInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ChunkInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::WebViewRPC.RpcEnvelopeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChunkInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChunkInfo(ChunkInfo other) : this() {
      chunkSetId_ = other.chunkSetId_;
      chunkIndex_ = other.chunkIndex_;
      totalChunks_ = other.totalChunks_;
      originalSize_ = other.originalSize_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ChunkInfo Clone() {
      return new ChunkInfo(this);
    }

    /// <summary>Field number for the "chunkSetId" field.</summary>
    public const int ChunkSetIdFieldNumber = 1;
    private string chunkSetId_ = "";
    /// <summary>
    /// 이 청크 세트의 고유 ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ChunkSetId {
      get { return chunkSetId_; }
      set {
        chunkSetId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "chunkIndex" field.</summary>
    public const int ChunkIndexFieldNumber = 2;
    private int chunkIndex_;
    /// <summary>
    /// 현재 청크 인덱스 (0부터 시작)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ChunkIndex {
      get { return chunkIndex_; }
      set {
        chunkIndex_ = value;
      }
    }

    /// <summary>Field number for the "totalChunks" field.</summary>
    public const int TotalChunksFieldNumber = 3;
    private int totalChunks_;
    /// <summary>
    /// 전체 청크 개수
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TotalChunks {
      get { return totalChunks_; }
      set {
        totalChunks_ = value;
      }
    }

    /// <summary>Field number for the "originalSize" field.</summary>
    public const int OriginalSizeFieldNumber = 4;
    private int originalSize_;
    /// <summary>
    /// 원본 메시지의 전체 크기 (검증용)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int OriginalSize {
      get { return originalSize_; }
      set {
        originalSize_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ChunkInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ChunkInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ChunkSetId != other.ChunkSetId) return false;
      if (ChunkIndex != other.ChunkIndex) return false;
      if (TotalChunks != other.TotalChunks) return false;
      if (OriginalSize != other.OriginalSize) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ChunkSetId.Length != 0) hash ^= ChunkSetId.GetHashCode();
      if (ChunkIndex != 0) hash ^= ChunkIndex.GetHashCode();
      if (TotalChunks != 0) hash ^= TotalChunks.GetHashCode();
      if (OriginalSize != 0) hash ^= OriginalSize.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ChunkSetId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ChunkSetId);
      }
      if (ChunkIndex != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ChunkIndex);
      }
      if (TotalChunks != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TotalChunks);
      }
      if (OriginalSize != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(OriginalSize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ChunkSetId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ChunkSetId);
      }
      if (ChunkIndex != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ChunkIndex);
      }
      if (TotalChunks != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(TotalChunks);
      }
      if (OriginalSize != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(OriginalSize);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ChunkSetId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChunkSetId);
      }
      if (ChunkIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChunkIndex);
      }
      if (TotalChunks != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TotalChunks);
      }
      if (OriginalSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(OriginalSize);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ChunkInfo other) {
      if (other == null) {
        return;
      }
      if (other.ChunkSetId.Length != 0) {
        ChunkSetId = other.ChunkSetId;
      }
      if (other.ChunkIndex != 0) {
        ChunkIndex = other.ChunkIndex;
      }
      if (other.TotalChunks != 0) {
        TotalChunks = other.TotalChunks;
      }
      if (other.OriginalSize != 0) {
        OriginalSize = other.OriginalSize;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ChunkSetId = input.ReadString();
            break;
          }
          case 16: {
            ChunkIndex = input.ReadInt32();
            break;
          }
          case 24: {
            TotalChunks = input.ReadInt32();
            break;
          }
          case 32: {
            OriginalSize = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ChunkSetId = input.ReadString();
            break;
          }
          case 16: {
            ChunkIndex = input.ReadInt32();
            break;
          }
          case 24: {
            TotalChunks = input.ReadInt32();
            break;
          }
          case 32: {
            OriginalSize = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
