// AUTO-GENERATED by protoc-gen-webviewrpc
// JavaScript Client: HelloServiceClient

// Import encoding/decoding functions for each method
import { encodeHelloRequest, decodeHelloResponse, } from './hello_world.js';

export class HelloServiceClient {
  /**
   * @param {WebViewRpcClient} rpcClient
   */
  constructor(rpcClient) {
    this.rpcClient = rpcClient;
  }

  
  /**
   * async SayHello
   * @param { HelloRequest } requestObj
   * @returns {Promise< HelloResponse >}
   */
  async SayHello(requestObj) {
    // 1) encode requestObj => Uint8Array
    const reqBytes = encodeHelloRequest(requestObj);
    // 2) callMethod => Promise<Uint8Array>
    const respBytes = await this.rpcClient.callMethod("HelloService.SayHello", reqBytes);
    // 3) decode => responseObj
    const respObj = decodeHelloResponse(respBytes);
    return respObj;
  }
  
}
