// AUTO-GENERATED by protoc-gen-webviewrpc
// JavaScript Client: HelloServiceClient

import { WebViewRpcClient } from "app-webview-rpc";
import { encodeHelloRequest, decodeHelloResponse } from './hello_world.js';

/**
 * Client for HelloService
 */
export class HelloServiceClient {
  /**
   * @param {WebViewRpcClient} rpcClient
   */
  constructor(rpcClient) {
    this._rpc = rpcClient;
  }

  
  /**
   * [one-way] Request -> Response
   * @param {HelloRequest} request
   * @returns {Promise<HelloResponse>}
   */
  async SayHello(request) {
    const requestBytes = encodeHelloRequest(request);
    const responseBytes = await this._rpc.callMethod(
      "HelloService.SayHello",
      requestBytes
    );
    return decodeHelloResponse(responseBytes);
  }
  
}
